version: "3.9"
services:
  better_auth:
    image: mongo:7
    container_name: better_auth
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: betterauth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
